### ISSUE TITLE
Unable to remove playlist using playlist_manager.py

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#133]
I've been trying to remove since updating to https://github.com/blacktwin/JBOPS/commit/63298cbb639fb71ecd329b2aec5ad227a762ba72. It says it has deleted the playlist and script finishes but it still shows when doing an --action show on the user. This also affects the --action update argument and a new playlist gets created instead. This is no error I get so it's really not easy to pinpoint what it may be hitting when it tries to remove playlists. It did work before the code had been updated with the --allLibraries option.

**Comment by blacktwin** [comment]
Show me your arguments.

**Comment by irodimus** [comment]
Well, we can do the popularMovies ones as it doesn't delete the previous playlist when updating. So, I create the playlist first:
```
python playlist_manager.py --jbop popularMovies --libraries "Movies" --action add --days 30 --top 25 --self
```
Works as expected, creating the playlist "Most Popular Movies (30 Days)". Then I just do the update as I've done previously:
```
python playlist_manager.py --jbop popularMovies --libraries "Movies" --action update --days 30 --top 25 --self
```
This gives me this result:
```
Deleting the playlist(s)...
Creating playlist(s)...
...Added Most Popular Movies (30 Days) playlist to 'admin'.
Done.
```
This then shows the "old" playlist and the new playlist in the Playlist section in Plex for the admin user. I've set this up to run to update automatically and it had worked for a couple of months already. It just stopped once I decided to update before the new changes were completed maybe around beginning of December.

I did also try to remove a specific playlist and it said it did but still showed when tested. I used something like this:
```
python playlist_manager.py --action remove --playlists "Most Popular Movies (30 Days)" --self
```

**Comment by blacktwin** [comment]
Ok I'm seeing the same thing now. Can't remove. I'll let you know when it's fixed.

Also, side note: you don't need `--self` if not using `--users`. You only need `--self` when you are using the actions for other users and want to include your admin account.

**Comment by blacktwin** [comment]
Ok should be fixed. The issue was, as in the commit notes, the title was being capitalized "Popular TV Shows" turned into "Popular Tv Shows" and due to how the removal works for the Popular playlists (exact match) this would cause the removal to skip past the "Popular Tv Shows" Playlist because it was looking for"Popular TV Shows".

Can you confirm its working on your end?

**Comment by irodimus** [comment]
This appears to work for the Most Popular playlists now. I did try to remove a playlist I shared with a user and it did not work. Here is an example:
```
python playlist_manager.py --action share --playlists Arrowverse --user Guest
```
This adds the playlist as usual. I then try to remove it using:
```
python playlist_manager.py --action remove --playlists Arrowverse --user Guest
```
I get the usual result:
```
Deleting the playlist(s)...
Done.
``
It still shows up the playlist in their list. Is removing a user's playlist possible or is that only for the admin user?

**Comment by blacktwin** [comment]
```
python playlist_manager.py --action remove --playlists Arrowverse --user Guest
```

Should work now. 

```
python playlist_manager.py --action remove --allPlaylists --user Guest
```

will be next.

**Comment by blacktwin** [comment]
And updated again to allow for `--allPlaylists` to function properly.

```
python playlist_manager.py --action remove --allPlaylists --user Guest
```

Thanks for working through this with me. I really appreciate your patience. Please let me know if everything is working correctly.

**Comment by irodimus** [comment]
Well the remove option worked and boy did it. So was able to remove the Guest's playlist no problems, but I noticed that the last user (user3) when using the show option:
```
python playlist_manager.py --action show --allLibraries --allUsers
```
would show the admin user's playlists, all of them even though I never shared them:
```
Displaying the user's playlist(s)...
user1's current playlist(s):
user2's current playlist(s):
user3's current playlist(s): 2 Days in New York, Blue Streak
Done.
```
I proved this by using:
```
python playlist_manager.py --action show --allLibraries --allUsers --self
```
giving me:
```
Displaying the user's playlist(s)...
user1's current playlist(s):
user2's current playlist(s):
user3's current playlist(s): 2 Days in New York, Blue Streak
admin's current playlist(s): 2 Days in New York, Blue Streak
Done.
```
but I didn't know this at the time. Now these are just examples now but I had 4 playlists in the admin user's and attempted to erase the user3's playlist using:
```
python playlist_manager.py --action remove --allPlaylists --user user3
```
and it gave me this result:
```
Deleting the playlist(s)...
...Deleted Playlist: 2 Days in New York for 'user3'.
...Deleted Playlist: Blue Streak for 'user3'.
Done.
```
Well this turned out to also delete the admin's playlists. I wasn't sure why but I did some investigating and it turns out that I had stopped sharing libraries with user3 but kept the account. I decided to delete it from sharing with my server and the problem went away once I did a show playlist again for all users. But I went further and stopped sharing libraries to user2, which was next up the list and when I did a show playlist command, his playlist now showed the admin user's playlists. Initially, when I found this out, user2 had a playlist they did with one movie, but when testing this method, his playlist listed ended up being the admin's playlists. 

So somewhere, the code is giving that last inactive user the admin playlists or at least showing the last user with with whatever the playlists the admin account currently has. I hope this made sense and I ain't even upset. I can always recreate those playlist. I'll keep testing.

**Comment by irodimus** [comment]
It turns out that any user that you share with, but does not have any shared libraries, will display the admin's playlist.

**Comment by blacktwin** [comment]
Awesome find! Thanks I'll look into why this is happening. Again, THANKS!!!

**Comment by blacktwin** [comment]
Sorry about your playlists.

**Comment by irodimus** [comment]
No worries on those playlists. I did try commit 
https://github.com/blacktwin/JBOPS/commit/b5c7261c3b31dbbd38db1820d61d9a98c5f70d0f although I'm not sure if you had fixed that issue yet. When I do a show now though, no playlists are seen from any of the users.

**Comment by blacktwin** [comment]
What is your command look like?

**Comment by irodimus** [comment]
I used this:
```
python playlist_manager.py --action show --allLibraries --allUsers --self
```
Is using `--allLibraries' now necessary to run the show command?

**Comment by blacktwin** [comment]
`--allLibraries` and `--allPlaylists` should only be needed when defining which to use for creating or sharing or removing.

`python2 playlist_manager.py --action show --allUsers`

Just pushed another update. Now the above works as it should.

**Comment by irodimus** [comment]
Ah, nevermind. Previously if `allLibraries` wasn't there, I would get a This function requires the use of all libraries or something like that. I don't get it now. I will try the new commit.
